### ISSUE TITLE
generatorviewgenerate is not defined

### ISSUE THREAD

**Issue by damionx7** [GrantMoyer/keeweb-plugin-passphrase-generator#1]
keeweb version : 1.14.0
OS : mac catalina 10.15.0

Using your repo address: https://grantmoyer.github.io/keeweb-plugin-passphrase-generator/ gives an error : Error loading plugin manifest
<img width="1440" alt="Screenshot 2020-04-20 at 2 47 42 PM" src="https://user-images.githubusercontent.com/6530843/79735424-e489a800-8315-11ea-8d4e-ad6165d23cb5.png">

Then i uploaded in on website and tried, it gives me the following error:

<img width="1440" alt="Screenshot 2020-04-20 at 2 45 36 PM" src="https://user-images.githubusercontent.com/6530843/79735288-a8eede00-8315-11ea-9cde-d42b2557bb6a.png">

what to do?

**Comment by GrantMoyer** [comment]
This happened because my user page configuration was interfering with my project pages. I believe I've fixed the issue, but it may take a few hours for the change to filter through caches. I'll check back in a few hours and close this issue if it's been fixed or investigate further if needed.

**Comment by GrantMoyer** [comment]
There was another issue related to you second error. I'd made a typo, which my earlier version of Firefox apparently ignored. It should be fixed by 42613fc.

**Comment by damionx7** [comment]
thanks . the issue is solved now.
