### ISSUE TITLE
doesn't generate passphrases

### ISSUE THREAD

**Issue by illionas** [GrantMoyer/keeweb-plugin-passphrase-generator#2]
````
VM115:45 Uncaught TypeError: Cannot read property 'getBytes' of undefined
    at get_random_index (eval at <anonymous> (index.html:1), <anonymous>:45:36)
    at eval (eval at <anonymous> (index.html:1), <anonymous>:18:62)
    at Function.from (<anonymous>)
    at f.GeneratorView.generate (eval at <anonymous> (index.html:1), <anonymous>:18:4)
    at f.render (index.html:1)
    at f.presetChange (index.html:1)
    at f.eventListener (index.html:1)
    at HTMLDivElement.e (index.html:1)
````

I've successfully installed the plugin. i can select the "passphrase" dropdown. However, it doesn't generate passphrases. I've looked into the devtools to find the error in the console which i have pasted above.

**Comment by GrantMoyer** [comment]
Hi @illionas, I can't reproduce this in firefox or the desktop app. Which browser are you using?

**Comment by GerritPlehn** [comment]
Exactly the same error for me.
Using keeweb desktop 1.18.7 on Linux Kernel 5.13.13 (https://github.com/keeweb/keeweb/releases/download/v1.18.7/KeeWeb-1.18.7.linux.x64.deb)

**Comment by GrantMoyer** [comment]
Thanks for the additional info @GerritPlehn. Could you also tell me which version of which Linux distribution you're using?

**Comment by GerritPlehn** [comment]
@GrantMoyer ArcoLinux (an Arch variant), so it's a rolling release.

https://github.com/GrantMoyer/keeweb-plugin-passphrase-generator/blob/42613fcfc5ffe631eb9654dc287619f270cb404e/plugin.js#L45
I set a breakpoint here to inspect, and the Kdbxweb object does indeed not have a `Random` property, but `Kdbxweb.CryptoEngine.random()` seems to do the trick. But I'm not sure about the real difference between them.

**Comment by GrantMoyer** [comment]
@GerritPlehn Ah, oops. I hadn't been using the latest version of KeeWeb desktop. Looks like the Random interface was indeed moved into CryptoEngine.

**Comment by GerritPlehn** [comment]
Awesome, can confirm the fix working for me :+1:
